HastaneOtomasyonApp/HastaneOtomasyonApp/Controllers/MuayeneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HastaneOtomasyonApp.Data;
using HastaneOtomasyonApp.Models;

namespace HastaneOtomasyonApp.Controllers
{
    public class MuayeneController : Controller
    {
        private readonly HastaneOtomasyonDBContext _context;

        public MuayeneController(HastaneOtomasyonDBContext context)
        {
            _context = context;
        }

        // GET: Muayene
        public async Task<IActionResult> Index()
        {
            var hastaneOtomasyonDBContext = _context.Muayene.Include(m => m.Birim).Include(m => m.Doktor).Include(m => m.Hasta).Include(m => m.ÖdemeTipi);
            return View(await hastaneOtomasyonDBContext.ToListAsync());
        }

        // GET: Muayene/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var muayene = await _context.Muayene
                .Include(m => m.Birim)
                .Include(m => m.Doktor)
                .Include(m => m.Hasta)
                .Include(m => m.ÖdemeTipi)
                .FirstOrDefaultAsync(m => m.MuayeneID == id);
            if (muayene == null)
            {
                return NotFound();
            }

            return View(muayene);
        }

        // GET: Muayene/Create
        public IActionResult Create()
        {
            ViewData["BirimID"] = new SelectList(_context.Birim, "BirimID", "BirimAdı");
            ViewData["DoktorID"] = new SelectList(_context.Doktor, "DoktorID", "DoktorTamAdı");
            ViewData["HastaID"] = new SelectList(_context.Hasta, "HastaID", "HastaTamAdı");
            ViewData["ÖdemeTipiID"] = new SelectList(_context.ÖdemeTipi, "ÖdemeTipiID", "ÖdemeTipiAdı");
            return View();
        }

        // POST: Muayene/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MuayeneID,BirimID,HastaID,DoktorID,HastaGeçmişi,HastaTeşhis,HastaTedavi,Yazılanİlaçlar,ÖdemeTipiID")] Muayene muayene)
        {
            if (ModelState.IsValid)
            {
                _context.Add(muayene);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BirimID"] = new SelectList(_context.Birim, "BirimID", "BirimAdı", muayene.BirimID);
            ViewData["DoktorID"] = new SelectList(_context.Doktor, "DoktorID", "DoktorTamAdı", muayene.DoktorID);
            ViewData["HastaID"] = new SelectList(_context.Hasta, "HastaID", "HastaTamAdı", muayene.HastaID);
            ViewData["ÖdemeTipiID"] = new SelectList(_context.ÖdemeTipi, "ÖdemeTipiID", "ÖdemeTipiAdı", muayene.ÖdemeTipiID);
            return View(muayene);
        }

        // GET: Muayene/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var muayene = await _context.Muayene.FindAsync(id);
            if (muayene == null)
            {
                return NotFound();
            }
            ViewData["BirimID"] = new SelectList(_context.Birim, "BirimID", "BirimAdı", muayene.BirimID);
            ViewData["DoktorID"] = new SelectList(_context.Doktor, "DoktorID", "DoktorTamAdı", muayene.DoktorID);
            ViewData["HastaID"] = new SelectList(_context.Hasta, "HastaID", "HastaTamAdı", muayene.HastaID);
            ViewData["ÖdemeTipiID"] = new SelectList(_context.ÖdemeTipi, "ÖdemeTipiID", "ÖdemeTipiAdı", muayene.ÖdemeTipiID);
            return View(muayene);
        }

        // POST: Muayene/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MuayeneID,BirimID,HastaID,DoktorID,HastaGeçmişi,HastaTeşhis,HastaTedavi,Yazılanİlaçlar,ÖdemeTipiID")] Muayene muayene)
        {
            if (id != muayene.MuayeneID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(muayene);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MuayeneExists(muayene.MuayeneID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BirimID"] = new SelectList(_context.Birim, "BirimID", "BirimAdı", muayene.BirimID);
            ViewData["DoktorID"] = new SelectList(_context.Doktor, "DoktorID", "DoktorTamAdı", muayene.DoktorID);
            ViewData["HastaID"] = new SelectList(_context.Hasta, "HastaID", "HastaTamAdı", muayene.HastaID);
            ViewData["ÖdemeTipiID"] = new SelectList(_context.ÖdemeTipi, "ÖdemeTipiID", "ÖdemeTipiAdı", muayene.ÖdemeTipiID);
            return View(muayene);
        }

        // GET: Muayene/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var muayene = await _context.Muayene
                .Include(m => m.Birim)
                .Include(m => m.Doktor)
                .Include(m => m.Hasta)
                .Include(m => m.ÖdemeTipi)
                .FirstOrDefaultAsync(m => m.MuayeneID == id);
            if (muayene == null)
            {
                return NotFound();
            }

            return View(muayene);
        }

        // POST: Muayene/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var muayene = await _context.Muayene.FindAsync(id);
            _context.Muayene.Remove(muayene);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MuayeneExists(int id)
        {
            return _context.Muayene.Any(e => e.MuayeneID == id);
        }
    }
}

HastaneOtomasyonApp/HastaneOtomasyonApp/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <strong>Copyright</strong>
    Tüm hakları saklıdır.
    <div class="float-right d-none d-sm-inline-block">
        <b>Versiyon</b> 1.2.0
    </div>
</footer>

HastaneOtomasyonApp/HastaneOtomasyonApp/Views/Shared/_Header.cshtml
<nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">İletişim</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu MESAJLAR KISMI-->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Levent Atahanlı
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Hasta kayıtlarını gönderebilir misiniz?</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Saat Önce</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Suat Birtan
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Mesajınızı aldım.</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 5 Saat Önce</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Ela Altındağ
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">En kısa sürede arayacağım.</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 13 Saat Önce</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">Tüm Mesajları Gör</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu ZİL KISMI-->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">7 Bildirim</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 yeni mesaj
                    <span class="float-right text-muted text-sm">3 dakika</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 Yeni Rapor
                    <span class="float-right text-muted text-sm">2 gün</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">Tüm Bildirimleri Gör</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

HastaneOtomasyonApp/HastaneOtomasyonApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Baslik"]</title>

    @*--------------------------------burada style linkleri vardı*@

    <partial name="_Styles" />

</head>
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__wobble" src="~/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar -->
      @*-----------------------------------------------------burada header vardı*@
        <partial name="_Header" />


        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
       @*---------------------------------------------burada sidebar vardı*@

        <partial name="_Sidebar" />



        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">@ViewData["SayfaBasligi"]</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a asp-controller="@(ViewContext.RouteData.Values["Controller"])" asp-action="Index">@(ViewContext.RouteData.Values["Controller"])</a></li>
                                
                                <li class="breadcrumb-item active"> @(ViewContext.RouteData.Values["Action"])</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            
            @RenderBody()


            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        @*--------------------------------------------burada footer vardı.*@


        <partial name="_Footer" />

    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
   @*-------------------------burada scriptler vardı*@

    <partial name="_Scripts" />

</body>
</html>

HastaneOtomasyonApp/HastaneOtomasyonApp/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Baslik"]</title>

    @*--------------------------------burada style linkleri vardı*@

    <partial name="_Styles" />

</head>
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__wobble" src="~/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar -->
      @*-----------------------------------------------------burada header vardı*@
        <partial name="_Header" />


        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
       @*---------------------------------------------burada sidebar vardı*@

        <partial name="_Sidebar" />



        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            @*------------------------------------------burada content header vardı*@
            <!-- /.content-header -->
            <!-- Main content -->
            
            @RenderBody()


            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        @*--------------------------------------------burada footer vardı.*@


        <partial name="_Footer" />

    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
   @*-------------------------burada scriptler vardı*@

    <partial name="_Scripts" />

</body>
</html>

HastaneOtomasyonApp/HastaneOtomasyonApp/Views/Shared/_Scripts.cshtml
<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- overlayScrollbars -->
<script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="~/dist/js/adminlte.js"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="~/plugins/jquery-mousewheel/jquery.mousewheel.js"></script>
<script src="~/plugins/raphael/raphael.min.js"></script>
<script src="~/plugins/jquery-mapael/jquery.mapael.min.js"></script>
<script src="~/plugins/jquery-mapael/maps/usa_states.min.js"></script>
<!-- ChartJS -->
<script src="~/plugins/chart.js/Chart.min.js"></script>

<!-- AdminLTE for demo purposes -->
<script src="~/dist/js/demo.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="~/dist/js/pages/dashboard2.js"></script>

HastaneOtomasyonApp/HastaneOtomasyonApp/Views/Shared/_Sidebar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a asp-controller="Home" asp-action="Index" class="brand-link">
        <img src="~/dist/img/logo.png" alt="Hastane Otomasyonu" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light"><small>HYS</small></span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/dist/img/kullanıcıicon.png" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Batuhan & Muhammed</a>
            </div>
        </div>

        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a asp-controller="Home" asp-action="Index" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Home" ? "active" : "")">
                        <i class="nav-icon fas fa-home"></i>
                        <p>
                            ANA SAYFA
                            @*<i class="right fas fa-angle-left"></i>*@
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a asp-controller="Muayene" asp-action="Index" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Hasta" ? "active" : "")">
                        <i class="fas fa-notes-medical"></i>
                        <p class="ml-lg-1">
                            MUAYENE KAYIT
                            @*<i class="right fas fa-angle-left"></i>*@
                        </p>
                    </a>
                </li>

                <li class="nav-item @(new string[] { "Hasta","Doktor","Birim","ÖdemeTipi"}.Any(ViewContext.RouteData.Values["Controller"].ToString().Equals)?"menu-open":"")">
                    <a href="#" class="nav-link @(new string[] { "Hasta","Doktor","Birim","ÖdemeTipi"}.Any(ViewContext.RouteData.Values["Controller"].ToString().Equals)?"active":"")">
                        <i class="nav-icon fas fa-bars"></i>
                        <p>
                            KAYITLAR
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Hasta" asp-action="Index" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Hasta" ? "active" : "") ">
                                <i class="fas fa-user-friends nav-icon"></i>
                                <p>HASTA</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Doktor" asp-action="Index" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Doktor" ? "active" : "") ">
                                <i class="fa fa-user-md nav-icon"></i>
                                <p>DOKTOR</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Birim" asp-action="Index" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Birim" ? "active" : "") " )">
                                <i class="far fa-building nav-icon"></i>
                                <p>BİRİM</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="ÖdemeTipi" asp-action="Index" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "ÖdemeTipi" ? "active" : "") " )">
                                <i class="fas fa-lira-sign nav-icon"></i>
                                <p>ÖDEME TİPİ</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item @(new string[] { "Laboratuvar"}.Any(ViewContext.RouteData.Values["Controller"].ToString().Equals)?"menu-open":"")">
                    <a href="#" class="nav-link @(new string[] {"Laboratuvar"}.Any(ViewContext.RouteData.Values["Controller"].ToString().Equals)?"active":"")">
                        <i class="nav-icon fas fa-chart-pie"></i>
                        <p>
                            LABORATUVAR
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Laboratuvar" asp-action="Index" class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Oda" ? "active" : "") ">
                                <i class="fas fa-flask nav-icon"></i>
                                <p>LABORATUVAR KAYIT</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

HastaneOtomasyonApp/HastaneOtomasyonApp/Views/Shared/_Styles.cshtml
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">


<!-- Theme style -->
<link rel="stylesheet" href="~/dist/css/adminlte.min.css">